const fs = require('fs');
const path = require('path');

const csvData = `EMPLOYEE NAME,1 (Tue),2 (Wed),3 (Thu),4 (Fri),5 (Sat),6 (Sun),7 (Mon),8 (Tue),9 (Wed),10 (Thu),11 (Fri),12 (Sat),13 (Sun),14 (Mon),15 (Tue),16 (Wed),17 (Thu),18 (Fri),19 (Sat),20 (Sun),21 (Mon),22 (Tue),23 (Wed),24 (Thu),25 (Fri),26 (Sat),27 (Sun),28 (Mon),29 (Tue),30 (Wed),WORKING DAYS,PRESENT,ABSENT
RAJESH DABBAKUTI,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
DURGA PRASAD MANDAVA,P,P,P,P,OFF,OFF,OFF,P,P,A,A,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,15,6
PRATHYUSH RAJ BONTHA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
PRANEETH RAJ BONTHA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,A,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
SATYANARAYANA REDDY AKKALA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
SAGAR ALAPATI,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
SHAHID SHAIK,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,A,A,A,OFF,OFF,A,A,A,A,,OFF,OFF,,,,21,10,11
RAFI MOHAMMAD,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,A,P,,OFF,OFF,,,,21,16,5
ZAKEER HUSSAIN MOHAMMAD,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
MAHABOOB SUBHANI SHAIK,P,P,A,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,0.5P,A,A,A,OFF,OFF,A,A,P,P,,OFF,OFF,,,,21,10.5,10.5
PURNA VENKATA KRISHNA SAI PATTEM,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
SRINIVAS MANNEM,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,A,A,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,15,6
ANIL KUMAR ULLAMGUNTA,P,P,P,A,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,A,A,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,14,7
VENKATA RAMESH POLISETTY,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
SURENDRA KOLATAM,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,A,A,OFF,OFF,,,,21,16,5
LEELA KRISHNA DASARI,P,A,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
SHILONI SASTRY DUNNA,P,P,P,P,OFF,OFF,OFF,A,A,A,A,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,13,8
BHAVANI SHANKAR KOMMURI,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,A,,OFF,OFF,,,,21,16,5
VIJAY KUMAR NALIGILA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,A,A,A,A,OFF,OFF,A,A,A,A,A,OFF,OFF,,,,21,9,12
LALITH VENKAT SAI KOTA,P,P,P,A,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
LIVEEJU BORUGADDA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
MOHIDDIN MD,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
JYOTHI SWAROOP CH,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,A,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
FHAYAZ AHAMMAD SHAIK,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,A,P,,OFF,OFF,,,,21,16,5
DHARMA TEJA NAMA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,A,P,P,P,,OFF,OFF,,,,21,16,5
VIJAY BHASKAR DEVARAPALLI,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,A,A,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,15,6
ABDUL HAMEED,P,P,P,P,OFF,OFF,OFF,A,A,A,A,OFF,OFF,A,A,A,A,A,OFF,OFF,A,A,A,A,A,OFF,OFF,A,A,A,21,4,17
VIJAYA SAI KRISHNA KEERTHI,0.5P,P,P,P,OFF,OFF,OFF,A,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,15.5,5.5
RAKESH NARAGARLA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
SYAM VENKATA SAI NARALASETTY,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
PUSAPATI MANI VARMA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
KURRA SIVA NAGA NIKHIL KRISHNA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
GUDAVALLI SURENDRA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
SURESH DABBAKUTI,A,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
ABHISHEK ANNAVARAPU,A,A,A,A,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,13,8
NAGA VENU ATLA,A,A,A,A,OFF,OFF,OFF,A,A,A,A,OFF,OFF,A,A,A,A,A,OFF,OFF,A,A,A,A,A,OFF,OFF,A,A,A,21,0,21
 NAGA BABU DIVIDEVARA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
NAVAKANTH GATTU,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
JUBEAR AHAMMED SHAIK,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,A,P,,OFF,OFF,,,,21,16,5
YEHOSHUVA GOLLAMUDI,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,A,P,,OFF,OFF,,,,21,16,5
KARTHIK DIVIDEVARA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
SANJAY MAMILLA ,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
JAFFER SHAIK,P,P,A,A,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,15,6
NAGA SASIDHAR REDDY AKKALA ,P,P,P,P,OFF,OFF,OFF,P,P,P,A,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
KUTUBUDDIN SHAIK,P,P,A,A,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,15,6
DEVENDRA LUKKA,P,P,A,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
AADI REDDY CHEERALA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,A,A,P,P,,OFF,OFF,,,,21,15,6
DURGA SRI VENKATESWARLU VEMULA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,A,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
VENKATA RAMESH PENDYALA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
EMANI RAKESH,P,P,P,P,OFF,OFF,OFF,A,A,A,A,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,13,8
PAMU NAGENDRA REDDY,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
MOGALIPUVVU ANKAMMARAO,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,A,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,16,5
REHMAN BEIG SHAIK,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,17,4
SAI AVINASH BABU ARADHYULA,P,P,P,P,OFF,OFF,OFF,P,P,P,P,OFF,OFF,P,P,P,P,P,OFF,OFF,A,P,P,P,,OFF,OFF,,,,21,16,5
ANVESH BABU THATAPUDI,P,P,P,P,OFF,OFF,OFF,A,A,P,P,OFF,OFF,P,P,P,A,P,OFF,OFF,P,P,P,P,,OFF,OFF,,,,21,14,7`;

const exactMapping = {
  'RAJESH DABBAKUTI': 'DBS-306',
  'DURGA PRASAD MANDAVA': 'DBS-429',
  'PRATHYUSH RAJ BONTHA': 'DBS-550',
  'PRANEETH RAJ BONTHA': 'DBS-548',
  'SATYANARAYANA REDDY AKKALA': 'DBS-433',
  'SAGAR ALAPATI': 'DBS-540',
  'SHAHID SHAIK': 'DBS-513',
  'RAFI MOHAMMAD': 'DBS-512',
  'ZAKEER HUSSAIN MOHAMMAD': 'DBS-514',
  'MAHABOOB SUBHANI SHAIK': 'DBS-515',
  'PURNA VENKATA KRISHNA SAI PATTEM': 'DBS-554',
  'SRINIVAS MANNEM': 'DBS-549',
  'ANIL KUMAR ULLAMGUNTA': 'DBS-560',
  'VENKATA RAMESH POLISETTY': 'DBS-568',
  'SURENDRA KOLATAM': 'DBS-2514',
  'LEELA KRISHNA DASARI': 'DBS-2511',
  'SHILONI SASTRY DUNNA': 'DBS-2519',
  'BHAVANI SHANKAR KOMMURI': 'DBS-2512',
  'VIJAY KUMAR NALIGILA': 'DBS-566',
  'LALITH VENKAT SAI KOTA': 'DBS-2530',
  'LIVEEJU BORUGADDA': 'DBS-2555',
  'MOHIDDIN MD': 'DBS-2554',
  'JYOTHI SWAROOP CH': 'DBS-449',
  'FHAYAZ AHAMMAD SHAIK': 'DBS-511',
  'DHARMA TEJA NAMA': 'DBS-230',
  'VIJAY BHASKAR DEVARAPALLI': 'DBS-352',
  'ABDUL HAMEED': 'DBS-488',
  'VIJAYA SAI KRISHNA KEERTHI': 'DBS-327',
  'RAKESH NARAGARLA': 'DBS-424',
  'SYAM VENKATA SAI NARALASETTY': 'DBS-25114',
  'PUSAPATI MANI VARMA': 'DBS-25133',
  'KURRA SIVA NAGA NIKHIL KRISHNA': 'DBS-25132',
  'GUDAVALLI SURENDRA': 'DBS-25138',
  'SURESH DABBAKUTI': 'DBS-466',
  'ABHISHEK ANNAVARAPU': 'DBS-25159',
  'NAGA VENU ATLA': 'DBS-25158',
  'NAGA BABU DIVIDEVARA': 'DBS-2605',
  'NAVAKANTH GATTU': 'DBS-2604',
  'JUBEAR AHAMMED SHAIK': 'DBS-2606',
  'YEHOSHUVA GOLLAMUDI': 'DBS-2607',
  'KARTHIK DIVIDEVARA': 'DBS-2617',
  'SANJAY MAMILLA': 'DBS-2615',
  'JAFFER SHAIK': 'DBS-2616',
  'NAGA SASIDHAR REDDY AKKALA': 'DBS-2613',
  'KUTUBUDDIN SHAIK': 'DBS-2639',
  'DEVENDRA LUKKA': 'DBS-2640',
  'AADI REDDY CHEERALA': 'DBS-2648',
  'DURGA SRI VENKATESWARLU VEMULA': 'DBS-2649',
  'VENKATA RAMESH PENDYALA': 'DBS-2661',
  'EMANI RAKESH': 'DBS-2668',
  'PAMU NAGENDRA REDDY': 'DBS-2669',
  'MOGALIPUVVU ANKAMMARAO': 'DBS-2674',
  'REHMAN BEIG SHAIK': 'DBS-2684',
  'SAI AVINASH BABU ARADHYULA': 'DBS-2685',
  'ANVESH BABU THATAPUDI': 'DBS-2686'
};

function runExactImport() {
  const dbPath = path.join(__dirname, 'data', 'db.json');
  const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

  // Ensure Abdul Hameed exists in employees list
  let hameed = db.employees.find(e => e.id === 'DBS-488');
  if (!hameed) {
    hameed = {
      id: 'DBS-488',
      name: 'Abdul Hameed',
      department: 'AR Callers',
      role: 'AR Caller',
      roleType: 'Employee',
      isArchived: false,
      passwordHash: 'b45d2e7d7807c4d7e8b6285800d0246a',
      avatarColor: '#DC2626'
    };
    db.employees.push(hameed);
  }

  const lines = csvData.trim().split('\n');
  const existingOther = (db.attendance || []).filter(a => !a.date || !a.date.startsWith('2026-09'));
  let newAttendanceRecords = [...existingOther];

  let recordCount = 0;

  for (let i = 1; i < lines.length; i++) {
    const row = lines[i].split(',');
    const rawNameKey = row[0].trim();
    if (!rawNameKey) continue;

    const empId = exactMapping[rawNameKey];
    const emp = db.employees.find(e => e.id === empId);

    if (!emp) {
      console.error('ERROR: Could not find emp for key:', rawNameKey, empId);
      continue;
    }

    for (let day = 1; day <= 30; day++) {
      const val = (row[day] || '').trim().toUpperCase();
      const dayStr = String(day).padStart(2, '0');
      const dateStr = `2026-09-${dayStr}`;

      let status = null;
      if (val === 'P') {
        status = 'Present';
      } else if (val === 'A') {
        status = 'Absent';
      } else if (val === '0.5P' || val === '0.5 P' || val === 'HALF') {
        status = 'Half Day';
      } else if (val === 'OFF' || val === 'HOLIDAY') {
        status = 'Holiday / Off';
      }

      if (status) {
        newAttendanceRecords.push({
          id: `ATT-SEP-${dateStr}-${emp.id}`,
          employeeId: emp.id,
          employeeName: emp.name,
          department: 'AR Callers',
          date: dateStr,
          status: status,
          updatedAt: new Date().toISOString()
        });
        recordCount++;
      }
    }
  }

  db.attendance = newAttendanceRecords;
  fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), 'utf8');

  console.log('SUCCESS! September attendance database import finished perfectly.');
  console.log(`Total attendance records written to data/db.json: ${recordCount}`);
}

runExactImport();
